language: python
python:
  - "3.6"
services:
  - docker
#addons:
#  postgresql: "9.6"
env:
  - DOCKER_COMPOSE_VERSION=1.23.1
before_script:
#  - psql -c 'create database postgres;' -U postgres
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d
  - sleep 10
  - python3 manage.py makemigrations
  - python3 manage.py makemigrations auth_and_static
  - python3 manage.py makemigrations task_controller
  - python3 manage.py migrate
# command to install dependencies
install:
  - virtualenv venv --distribute
  - source venv/bin/activate
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run -m pytest
  - coverage report -m
after_script:
  - docker-compose down
after_success:
  - codecov -t 029a6193-db20-4e43-b6b5-ee39982a7528