# docker run --rm --name some-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres
# docker run --rm -d --hostname my-rabbit -p 5672:5672 -p 5671:5671 -p 15672:15672 -e RABBITMQ_DEFAULT_VHOST=my_vhost --name some-rabbit rabbitmq:3
# celery worker -A remoteexperements --loglevel=info --concurrency=2

version: "3"
services:
  bd:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: some-postgres
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - mynet
  queue:
    image: rabbitmq:3
    container_name: some-rabbit
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"
    networks:
      - mynet
    hostname: my-rabbit
  worker:
    build: .
    depends_on:
      - bd
      - queue
    environment:
      - GAC_DB_LOCALHOST=bd
      - GAC_QUEUE_LOCALHOST=queue
    networks:
      - mynet

networks:
  mynet:
